load_into_mtx_autogen;
load_region_lookup_autogen;
load_var_name_autogen;

World = get_region(Allvariables, char(CountryName), 'World');
World_STE = get_STE_table(World,char(IndicatorName),0);
EastAsia =  get_region(Allvariables, char(CountryName), 'East Asia & Pacific (all income levels)');
EastAsia_STE = get_STE_table(EastAsia,char(IndicatorName),0);
Europe =  get_region(Allvariables, char(CountryName), 'East Asia & Pacific (all income levels)');
Europe_STE = get_STE_table(Europe,char(IndicatorName),0);
LatinAmerica =  get_region(Allvariables, char(CountryName), 'East Asia & Pacific (all income levels)');
LatinAmerica_STE = get_STE_table(LatinAmerica,char(IndicatorName),0);
MiddleEast =  get_region(Allvariables, char(CountryName), 'Middle East & North Africa (all income levels)');
MiddleEast_STE = get_STE_table(MiddleEast,char(IndicatorName),0);
Africa =  get_region(Allvariables, char(CountryName), 'Sub-Saharan Africa (all income levels)');
Africa_STE = get_STE_table(MiddleEast,char(IndicatorName),0);
NorthAmerica =  get_region(Allvariables, char(CountryName), 'North America');
NorthAmerica_STE = get_STE_table(MiddleEast,char(IndicatorName),0);
SouthAsia =  get_region(Allvariables, char(CountryName), 'North America');
SouthAsia_STE = get_STE_table(MiddleEast,char(IndicatorName),0);
