%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Fernando\OneDrive\Documents\University of Missouri\Spring 2015\Artificial Intelligence\AI2-final\Datasets\All variables.xlsx
%    Worksheet: Definition and Source
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB using the Import Data wizard

%% Import the data
[~, ~, raw] = xlsread('Datasets\All variables.xlsx','Definition and Source','B2:B13');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);

%% Allocate imported array to column variable names
IndicatorName = cellVectors(:,1);

%% Clear temporary variables
clearvars raw cellVectors;