%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\Fernando\OneDrive\Documents\University of Missouri\Spring 2015\Artificial Intelligence\AI2-final\Datasets\All variables.xlsx
%    Worksheet: Data
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2015/04/25 23:45:01

%% Import the data
[~, ~, raw] = xlsread('Datasets/All variables.xlsx','Data','A2:A441');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);

%% Allocate imported array to column variable names
CountryName = cellVectors(:,1);

%% Clear temporary variables
clearvars raw cellVectors;