%% Vertical dependencies
Africa_STE_deps_2
EastAsia_STE_deps_2
Europe_STE_deps_2
LatinAmerica_STE_deps_2
MiddleEast_STE_deps_2
NorthAmerica_STE_deps_2
SouthAsia_STE_deps_2
World_STE_deps_2

%% Cross dependencies
Africa_STE_deps_2a
EastAsia_STE_deps_2a
Europe_STE_deps_2a
LatinAmerica_STE_deps_2a
MiddleEast_STE_deps_2a
NorthAmerica_STE_deps_2a
SouthAsia_STE_deps_2a
World_STE_deps_2a